---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Debian)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
